datasets_info:
  OCT2017:
    url: https://data.mendeley.com/public-files/datasets/rscbjbr9sj/files/5699a1d8-d1b6-45db-bb92-b61051445347/file_downloaded
    archive_type: tar.gz
    extract_to: OCT2017

  COVID19_Radiography:
    url: https://www.kaggle.com/api/v1/datasets/download/tawsifurrahman/covid19-radiography-database
    archive_type: zip
    extract_to: COVID-19_Radiography_Dataset

  TB_Chest:
    url: https://www.kaggle.com/api/v1/datasets/download/tawsifurrahman/tuberculosis-tb-chest-xray-dataset
    archive_type: zip
    extract_to: TB_Chest_Radiography_Database

  Brain_MRI:
    url: https://www.kaggle.com/api/v1/datasets/download/masoudnickparvar/brain-tumor-mri-dataset
    archive_type: zip
    extract_to: .

categories:
  lung-normal:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - Normal/images
      - dataset: TB_Chest
        paths:
          - Normal

  lung-covid:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - COVID/images

  lung-opacity:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - Lung_Opacity/images

  lung-viral-pneumonia:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - Viral Pneumonia/images

  lung-tuberculosis:
    sources:
      - dataset: TB_Chest
        paths:
          - Tuberculosis

  brain-glioma:
    sources:
      - dataset: Brain_MRI
        paths:
          - Training/glioma
          - Testing/glioma

  brain-meningioma:
    sources:
      - dataset: Brain_MRI
        paths:
          - Training/meningioma
          - Testing/meningioma

  brain-notumor:
    sources:
      - dataset: Brain_MRI
        paths:
          - Training/notumor
          - Testing/notumor

  brain-pituitary:
    sources:
      - dataset: Brain_MRI
        paths:
          - Training/pituitary
          - Testing/pituitary

  lung-oct-cnv:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - train/CNV
          - test/CNV

  lung-oct-dme:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - train/DME
          - test/DME

  lung-oct-drusen:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - train/DRUSEN
          - test/DRUSEN

  lung-oct-normal:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - train/NORMAL
          - test/NORMAL
