datasets_info:
  OCT2017:
    url: https://data.mendeley.com/public-files/datasets/rscbjbr9sj/files/5699a1d8-d1b6-45db-bb92-b61051445347/file_downloaded
    archive_type: tar.gz
    extract_to: OCT2017

  COVID19_Radiography:
    url: https://www.kaggle.com/api/v1/datasets/download/tawsifurrahman/covid19-radiography-database
    archive_type: zip
    extract_to: COVID-19_Radiography_Dataset

  TB_Chest:
    url: https://www.kaggle.com/api/v1/datasets/download/tawsifurrahman/tuberculosis-tb-chest-xray-dataset
    archive_type: zip
    extract_to: TB_Chest_Radiography_Database

  Brain_MRI:
    url: https://www.kaggle.com/api/v1/datasets/download/masoudnickparvar/brain-tumor-mri-dataset
    archive_type: zip
    extract_to: Brain_MRI

categories:
  lung-normal:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - COVID-19_Radiography_Dataset/Normal/images
      - dataset: TB_Chest
        paths:
          - TB_Chest_Radiography_Database/Normal

  lung-covid:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - COVID-19_Radiography_Dataset/COVID/images

  lung-opacity:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - COVID-19_Radiography_Dataset/Lung_Opacity/images

  lung-viral-pneumonia:
    sources:
      - dataset: COVID19_Radiography
        paths:
          - COVID-19_Radiography_Dataset/Viral Pneumonia/images

  lung-tuberculosis:
    sources:
      - dataset: TB_Chest
        paths:
          - TB_Chest_Radiography_Database/Tuberculosis

  brain-glioma:
    sources:
      - dataset: Brain_MRI
        paths:
          - Brain_MRI/Training/glioma
          - Brain_MRI/Testing/glioma

  brain-meningioma:
    sources:
      - dataset: Brain_MRI
        paths:
          - Brain_MRI/Training/meningioma
          - Brain_MRI/Testing/meningioma

  brain-notumor:
    sources:
      - dataset: Brain_MRI
        paths:
          - Brain_MRI/Training/notumor
          - Brain_MRI/Testing/notumor

  brain-pituitary:
    sources:
      - dataset: Brain_MRI
        paths:
          - Brain_MRI/Training/pituitary
          - Brain_MRI/Testing/pituitary

  lung-oct-cnv:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - OCT2017/CNV

  lung-oct-dme:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - OCT2017/DME

  lung-oct-drusen:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - OCT2017/DRUSEN

  lung-oct-normal:
    oct: true
    sources:
      - dataset: OCT2017
        paths:
          - OCT2017/NORMAL
