name: upload-merged-dataset

volumes:
  mergeddata:

services:
  extract-data:
    container_name: extract_merged_data
    image: python:3.11
    user: root
    volumes:
      - mergeddata:/data/merged_dataset
    working_dir: /data
    command:
      - bash
      - -c
      - |
          set -e
          echo "Creating target directory..."
          rm -rf /data/train /data/val /data/test /data/final_eval
          
          echo "Downloading merged_dataset.zip from NYU Box..."
          curl -L 'https://dl.boxcloud.com/d/1/b1!3KZhrOZRWT6nkw3ZTDqPTeY2B2YL1apwWxebj_AN-yRFaFwJZ3gVV23EXwJ42Myc05zDmeEaWbbUSEkO5TSkCMgDDM9gDx0gBy1teKKw9o4iSNagB0jPKJASzuGb1ZWU7mpvTV2XRkToy07A5agh-Ce9Jz4vEyh3TB2xTybV2IC7VypTZEZ3f3EWa6D2gX0O-4wYREYnsrprfLUM5eGi-MyEP-Ank7C6Q1Tyn379rzywA23LmhOcPM4MiAKetA1rP1Bzf_XustQIhSFf7r58vVOxguTJRJgH-V_ZBcpAaO4i-duTZEBbJmJw6T0YOOru35_Wp1OQZqsX4yYi3MNjkNhI5XGRVP2PolyNrHj5DOIwXkFTLq7H16xyEU4LfKfs6LlqMyeTqVNpxv8nla8HGT3FXx4Aq7WYaSJUNo6Dq2hcypdAVLf16Dh_20GqwXSV3kltXhf8CzTpgPBAP0IlVqm5R9uASWTrs-auviz9t8wNAxKLQ-ufhbLgwUoCNDvle_VWI2w5pY4Y7XmgsjC3kIb1UhF-7hu63d5MSgYEJDuQDHY7mIlymPjivsXJV6hskWBJPtdsqrviuJAM5ASAnjF-HPWaNNsRTltLMQWgDo8croq9hqXbs8lFMwLD1tjEgzwjvVpMtSiuvAeFKydGpn9HGB1ok8N0TSlDCELrGn1YGMQZZS-jl02a1uk5Veev9szE4sTGDCDhuWsF5YZbycZ1yul2M-RotMh8NsbsANRxx1h49in9pe0dnlkFp73Wt8r9Aw3gSdGmV4q-P6GW0jB6n9_z7Rrc5W7j9SbCr35pHEnmkct87msjaWj-yV60WzFDtlRHDAka5Udfdu8-7JYCI0ycYRujfyuH2XKP0MgH5vcJUX-NWewZDCzrNpk2NucPXiurDv_Va4GDhthOO_n_7R4yE_rn4OZ8NYRFzDvBI0zpviNWn8uFnSaA86LX7iWklOGVFAydwhkywDOwj2Xf6JV3CXcWoGj4J3XY2hnnBLXih2cEG7lZuFyGMAgl1ueCo5dSE0qAEXRkUILPoSaD8hEe_euqfrmJ1S8VaQKRrNOxoacPYkEwuMaeh4S_Mw8mS0IjUVQyWRIJ80QlhUA_7BAqnGSF7_gIeTgmBBUCK1ptGYq6ImhHxlyCO5rSSoghMPT-0zi0MKm3B2JFqRtpDF58N4COehnrho-l4U9EFtjzsjYoVdOTcD_O35cWbKYU5rU3V4MhofVvXgvbdxNR9LmKTTjXkY2fsVz7YNf9OKO2xh2g7wEPx8r5ZZKnLHfKp040qnhOTKceoER61Ay8vgxHuDeH6a26B0jYaiwvuzUqH2oZrgpwx1snB-k5j1QQfl8KZ_9QQj7PxrulfFCjmIgTVh1QKI3UrDF9cmwEs69_M5AGXdGZEzzpUbQxjFzDiSdx4BWorgCnTilfT76Ehd7KrYsYYls7GUvDRsJbXBshE84JmETRf9ELdRVIQidyNrFKf5XLmEUUYSGIl8aJzjETP7CG1fenGn770yCCIAL1koifqQ../download' -o merged_dataset.zip
          echo "Unzipping..."
          unzip -q merged_dataset.zip -d /data/merged_dataset
          rm -f merged_dataset.zip
          
          echo "Listing contents of /data after extract stage:"
          ls -l /data

  load-data:
    container_name: upload_merged_data
    image: rclone/rclone:latest
    volumes:
      - mergeddata:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
          if [ -z "$RCLONE_CONTAINER" ]; then
            echo "ERROR: RCLONE_CONTAINER is not set"
            exit 1
          fi

          echo "Cleaning up existing contents of object store..."
          rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

          echo "Uploading /data to object store..."
          rclone copy /data/merged_dataset/. chi_tacc:$RCLONE_CONTAINER \
            --progress \
            --transfers=32 \
            --checkers=16 \
            --multi-thread-streams=4 \
            --fast-list

          echo "Upload complete. Listing contents:"
          rclone lsd chi_tacc:$RCLONE_CONTAINER
