name: upload-merged-dataset

volumes:
  mergeddata:

services:
  extract-data:
    container_name: extract_merged_data
    image: python:3.11
    user: root
    volumes:
      - mergeddata:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        echo "Creating target directory..."
        rm -rf merged_dataset
        mkdir -p merged_dataset
        cd merged_dataset
        # curl -L https://nyu.box.com/shared/static/vj63o013r3pep3fklidza32ijxuullc3.zip \
        # curl -L https://nyu.box.com/shared/static/vj63o013r3pep3fklidza32ijxuullc3.zip -o merged_dataset.zip
        curl -L "https://dl.boxcloud.com/d/1/b1!6lY83yetneXZPL5o_eKSn3cilacDgsmuh50BLjw8UbUQhNYNNuiXUzFSCgD7GqSMlWvrXkshcfoQGjCoC2f9cmt-5sMtxSTtp3JpKGAnl9wy9t9Tb4XGtuvf51dE_YM4VEFJspECwj0oVCPB2y2LEFkE6hqPmd4J9Af9AjyMFCdHflkZhtlbLJ8Tpcv-diUzn1cNnSJhVQQ4jxALkt72R4rSiO7xrt0NckUFjb-3kxANV2OoUMJj-MBHhYni4ZTqI_Hsk8z6vlK7EM-QK5LgqgmeNFt58iPLYcrnVCXryjNCZ2fdnf_3LRwk8knJH3Ui4G589f2nCUYqDlN0exksBa6S8Njq7XXDaUg9sVEF39Ae_L7GfToPP4zk03-RQUtqVcn4Fw7jcbTbobiZ6pXdNSa8zKRf4y4-Ex5Y_BaFvreW0ergFTj9uGt76Ancq2siPs_RYzSJ0E1geLfo-ZAZDuSAs_ii1_CBaU65jXjqz1cuXtgvNQcfJ9KNVg6R8GwcaGKo7W0173hpnVKMz0k7GJY2uzw26FcmeCdJy77SBSRp8ad-aGXUVUD2Z3g9p9yMtqKSukR6I6HC0wVLJ_0vgG0o_Eo5LvvlrQMUtsm0yiTFu4bDdyBuZGl8W-Qh7uzvZxEVRKWPMXxbNeXSMQqrJPBFwW3WTBf3rt3PIH7bqZMSxi4km0bpqElC-7GIKfg5_DYSAqd_XHmchduxkAOnAlQrVKfwVy42UuowdsFmWCP_Va7r5zrHv0edx88fgH0bRA1bC16yvR4LHHitSaYliTH6xV2J8MSQ7e7SngMATJc9xuQYVuGE3CwxYJobNnNhEUAdZ65znmckBKQgFT3NNslJvyZPJmh7wfKpUSRhRG-C93IK9DFJjJsF8k1pjBfs_WXZwWGq5w2w4ZbU9M9n0IG2NKJ-Fwmr1aJ36UjrGZFXJL-1rMC0DjWbO-Wx4RRBNbAtnSF12Lp-4wP_pWc1kOaXa92OINUWg4MvoDcUp-q1mDz8v5aNr4jcQMrc3HDJaVhaa8DrixM5kY9gc61jg5QFzD3_RKWdRhS2L94IdodLUrTA1ucmXB5FKGZlXQq54RjueVpCaXejNOTYacQfwYNc6cQGK2MXHsvNuYzulTf-n1pGrOYw1eoWCR-i8heQKnffFwcQN5jml95X3N7U2uq8vHVcW9vtfOitdSpHU92ZIxuAHWezZnUIk_nQsAuWSNMxSZkAUO8SOQZJJac5nFRYpm02ZIS8-ROKb1e-NYFd-6uG4zOtiLWegQpD8ZIsymKlmwH2c-pLYC6vdWeGUSoEyN0JhZsb-ey-ZDcnbvOiI5Q6b6F7N3-DTTzVTAZHq06eUfS1WcztiwqbKaZTZu5BShb-Rt1-acTfRbIV-ZSN_D7zfLTMbaZ8II8Z25s0PesZQr6kKFUE6jXaAUfGScKS30HxbL16QBhEcgWqFN9ZIrv_mBqHHG2YtH8EsCSS1vDKrvcNDz_xFs0Cdn6eywOpsQPDDZ4kh-pitJpf3M0R726y0YI./download" \ 
          -o merged_dataset.zip
        # curl -L curl https://nyu.box.com/shared/static/vj63o013r3pep3fklidza32ijxuullc3.zip \
        
        echo "Unzipping..."
        unzip -q merged_dataset.zip -d /data/merged_dataset
        rm -f merged_dataset.zip

        echo "Listing contents of /data after extract stage:"
        ls -l /data/merged_dataset

  load-data:
    container_name: upload_merged_data
    image: rclone/rclone:latest
    volumes:
      - mergeddata:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Cleaning up existing contents of object store..."
        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

        echo "Uploading /data/merged_dataset to object store..."
        rclone copy /data/merged_dataset chi_tacc:$RCLONE_CONTAINER \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Upload complete. Listing contents:"
        rclone lsd chi_tacc:$RCLONE_CONTAINER
