name: upload-merged-dataset

volumes:
  mergeddata:

services:
  extract-data:
    container_name: extract_merged_data
    image: python:3.11
    user: root
    volumes:
      - mergeddata:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
          set -e
          echo "Creating target directory..."
          rm -rf /data/train /data/val /data/test /data/final_eval
          
          echo "Downloading merged_dataset.zip from NYU Box..."
          curl -L 'https://dl.boxcloud.com/shared/static/xxxxxxxxxxxxxxxxx' -o merged_dataset.zip
          echo "Unzipping..."
          unzip -q merged_dataset.zip -d /data
          rm -f merged_dataset.zip
          
          echo "Listing contents of /data after extract stage:"
          ls -l /data

  load-data:
    container_name: upload_merged_data
    image: rclone/rclone:latest
    volumes:
      - mergeddata:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
          if [ -z "$RCLONE_CONTAINER" ]; then
            echo "ERROR: RCLONE_CONTAINER is not set"
            exit 1
          fi

          echo "Cleaning up existing contents of object store..."
          rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

          echo "Uploading /data to object store..."
          rclone copy /data/. chi_tacc:$RCLONE_CONTAINER \
            --progress \
            --transfers=32 \
            --checkers=16 \
            --multi-thread-streams=4 \
            --fast-list

          echo "Upload complete. Listing contents:"
          rclone lsd chi_tacc:$RCLONE_CONTAINER
