version: "3"

volumes:
  merged_medical:

services:
  merge-data:
    container_name: etl_merge_data
    image: python:3.11
    user: root
    network_mode: host
    volumes:
      - merged_medical:/app/merged_dataset
      - ./downloads:/app/downloads 
      - ./datamerged2.py:/app/datamerged2.py:ro
      - ./datasets_config.yaml:/app/datasets_config.yaml:ro
    working_dir: /app
    command:
      - bash
      - -c
      - |
        set -e
        echo "Installing dependencies..."
        pip install --no-cache-dir requests pyyaml scikit-learn
        echo "Running data merge pipeline..."
        python3 datamerged2.py
        echo "Merge completed. Listing contents of merged_dataset:"
        find /app/merged_dataset | head

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - merged_medical:/data
      # - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
      - ~/.config/rclone:/root/.config/rclone:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi
        echo "Deleting existing contents of the container..."
        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true
        echo "Uploading merged dataset..."
        rclone copy /data chi_tacc:$RCLONE_CONTAINER \
        --progress \
        --transfers=32 \
        --checkers=16 \
        --multi-thread-streams=4 \
        --fast-list
        echo "Upload completed. Listing directories in the container:"
        rclone lsd chi_tacc:$RCLONE_CONTAINER
