name: upload-merged-dataset

volumes:
  mergeddata:

services:
  extract-data:
    container_name: extract_merged_data
    image: python:3.11
    user: root
    volumes:
      - mergeddata:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        echo "Creating target directory..."
        rm -rf merged_dataset
        mkdir -p merged_dataset
        cd merged_dataset
        # curl -L https://nyu.box.com/shared/static/vj63o013r3pep3fklidza32ijxuullc3.zip \
        # curl -L https://nyu.box.com/shared/static/vj63o013r3pep3fklidza32ijxuullc3.zip -o merged_dataset.zip
        # curl -L https://nyu.box.com/shared/static/vj63o013r3pep3fklidza32ijxuullc3.zip \

        curl -L https://dl.boxcloud.com/d/1/b1!7sw-Gwm5BZFZo-xLhUGjs96ISryGldiLz1iTcKSMX_AiXBVHQJd1GExW6S9z50AOmBsOHuk9R1Me2gEw98UqA1UPKnHbbrREUxi4dDzDnGUtClcjLGgbUSM0Vp0t_SIX_MX1wfe6R-BogtE5ZqZUNh9aTiefC2gz6lXDH3vOakz9v9QubTAQ26i9QuwPUP5Km3baEDalhkzd8LHTp7gfoEexG3dBGYIoAaTKy9H6UA-FSQmbjRE7gkUvE_2VCuEsBOBRWN5lqt12lj6_ZnGLNjcX9bGMSjtj7pEwWjcA6sR0CfiFbhJMW_y0ML4V6U9eAOHsMOgAAeIXniMLnA4Ihp9ibl-EcvDXNR42UTRH0FoSwPclyiNS8qupVN6SDTcYnrjBt9fAgeF0Uz1Bvk0KdDd4Ubpakc69Su3oAhqvKZjVI1OuT7P3stNDe4dyfaY4VcpKE_uL3bRzO43fpJNT9ntW1G65_oNeOv7S1yEis0TNBbm32wDu_S44nEqfkidzTrlpYj0DYHy9uVrfo8aQAnPFGO9jv7LjA4siePflPT0pDMR5kMTEPaWCPpWRGFKblX_gFbAozuz7Yg_rQ5wFiPOTjhtVlaIDfk3w_wUXFQxazsiZwemk4vbmRqwE1kf26qEMZHdk6uEi9IK3GYwSkNkCbAW1VK1Kd0NJYkraKgiY_mm-q5ZxxtjlbLQ46x0nsdEvDgi-4F32jB4YH68hjR8fclR21GyLf6gM9RoqsP2Zm0Qdutl6ikKu5mkuY4z1cQlZLhokWpM79pNcbEZbVjy2gIzA427ik5T9wCB_rqaG1X2ooqchpdd09Ih1FD4f0yr96A8d5Xizrp5Pk-1kxTaCFRnyW8og9NcS2PxpVkG-PU3r5jkeMQaSYdkLnzMipC2DS4AFrnnJ-rKJyC7ihlFAAJk9VtYaQ6Oy6sDqgqwjJltWQtGJFZZb-MzDKjXNUHAVB2obT0DwoHnmKhyqOnj5rQ1bX1LYjvJY7KVkALOEnR3oJiXks8ALCjyW0g0y-RB4iAYSTvuU0M50lnu09vXwzdHHrVO3rLvYGEfgN8HIzf0hIu1OTjeZVtfUQY66GXLR39yFPDnR7xJ0hemuwRA7ss1SFlLz8-QmmRNVEz_DmHzRCb8xr9W_5aToGrdg6TCX0yTyoewfbWbujGZIXH4AP4PUOMmhi2akHcaVGU3otAMZelOiG2hdVaXdNIvcfi3YOtAicf_gL2KnjSDvacQQLXnPz12w29zVZKArbIPLbi_qrlqVjC6SW_hBFdJ5K2xaiHMuUoVXf9H-lLs6xgmqLCbBV0_s8GxjDVULx_B8vi9LHMpLjmIGmIUbmuShdCfUyNmJ8GUzbj1xYKEUw1LRFnLVMPKY-tgnZnuHgmCmZk-UAkod0JeLL5AULF8zXUt-lKLdf8s-p4QD4NalI2TwsolZ-u42lPyW4WcPiJhPZVnJH9nIk_uj065FAdQ1K0vy-7Mb3b6j0f_oSyI7psYfnlToReVZR904e3vUk97M2ZUa2BU./download.zip \
          -o merged_dataset.zip
          
        echo "Unzipping..."
        unzip -q merged_dataset.zip 
        rm -f merged_dataset.zip

        echo "Listing contents of /data after extract stage:"
        ls -l /data

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - mergeddata:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Cleaning up existing contents of object store..."
        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

        echo "Uploading /data/merged_dataset to object store..."
        rclone copy /data/merged_dataset chi_tacc:$RCLONE_CONTAINER \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Upload complete. Listing contents:"
        rclone lsd chi_tacc:$RCLONE_CONTAINER
